"""Per-element invariants — the periodic-table foundation.

Loads `constellation/data/elements.json` (generated by
`scripts/build-elements-json.py` from NIST AME2020 + IUPAC + Cordero/Bondi/
Alvarez/Pauling sources) and exposes:

    Isotope            (mass_number, exact_mass, abundance)
    Element            full per-element record
    ElementTable       read-only registry, indexable by symbol or atomic number
    ELEMENTS           module-level singleton
    ELEMENT_SYMBOLS    canonical composition-axis ordering (by atomic number)
    ELEMENT_TYPES      legacy CHNOPS-6 view alias for the MS hot path
    MASSES, WEIGHTS    derived element-mass dict views (pinned to ELEMENTS by test)
    PROTON_MASS, ELECTRON_MASS, NEUTRON_MASS, ISOTOPE_MASS_DIFF, AVOGADRO

Tensors are CPU-resident at import; users move them with `.to(device)`.

Sources (declared in elements.json `source` block):
    - Isotope masses, abundances, standard atomic weights:
      NIST AME2020 (https://physics.nist.gov/PhysRefData/Compositions/).
    - Pauling electronegativity: Pauling 1960; Allred-Rochow for heavy elements.
    - Covalent radii: Cordero et al., Dalton Trans., 2008, 2832-2838.
    - vdW radii: Bondi 1964 (J. Phys. Chem. 68, 441); Alvarez 2013
      (Dalton Trans., 8617-8636).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from importlib import resources
from typing import Iterator

import torch

# ──────────────────────────────────────────────────────────────────────
# Fundamental physical constants
# ──────────────────────────────────────────────────────────────────────

PROTON_MASS: float = 1.00727646688
ELECTRON_MASS: float = 0.00054857990907
NEUTRON_MASS: float = 1.00866491595
# ¹³C minus ¹²C exact mass — the conventional "1 Da" spacing for
# nominal-mass binned isotope envelopes. Use exact per-element isotope
# masses (Element.isotopes) for high-resolution work.
ISOTOPE_MASS_DIFF: float = 1.0033548378
AVOGADRO: float = 6.02214076e23


# ──────────────────────────────────────────────────────────────────────
# Dataclasses
# ──────────────────────────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class Isotope:
    """A single stable (or representative) isotope of an element."""

    mass_number: int
    exact_mass: float  # NIST AME2020, Da
    abundance: float  # natural fraction in [0, 1]; 0.0 for radioactive-only


@dataclass(frozen=True, slots=True)
class Element:
    """Per-element invariants. Element-level, not molecule-level —
    structural features (degree, hybridization, in-ring) come from
    `core.structure.topology`, not from here."""

    symbol: str
    atomic_number: int
    monoisotopic_mass: float  # most-abundant isotope's exact mass
    standard_atomic_weight: float | None
    isotopes: tuple[Isotope, ...]  # full per-isotope list (NIST)
    pauling_electronegativity: float | None
    covalent_radius_pm: int | None
    vdw_radius_pm: int | None
    valence_electrons: int
    group: int  # IUPAC 1..18; lanthanides/actinides → -1
    period: int  # 1..7

    @property
    def average_mass(self) -> float:
        """Standard atomic weight, falling back to the abundance-weighted
        mean of stable isotopes if the standard value is undefined
        (radioactive-only elements)."""
        if self.standard_atomic_weight is not None:
            return self.standard_atomic_weight
        total_abun = sum(i.abundance for i in self.isotopes)
        if total_abun > 0:
            return sum(i.exact_mass * i.abundance for i in self.isotopes) / total_abun
        return self.monoisotopic_mass


# ──────────────────────────────────────────────────────────────────────
# Feature tensor column layout
# ──────────────────────────────────────────────────────────────────────

# Order is part of the public contract — graph-NN code that hard-codes
# column indices depends on this.
FEATURE_COLUMNS: tuple[str, ...] = (
    "atomic_number",
    "monoisotopic_mass",
    "standard_atomic_weight",
    "pauling_electronegativity",
    "covalent_radius_pm",
    "vdw_radius_pm",
    "valence_electrons",
    "group",
    "period",
)


def _element_to_feature_row(element: Element) -> list[float]:
    def _f(v):
        return float("nan") if v is None else float(v)

    return [
        float(element.atomic_number),
        _f(element.monoisotopic_mass),
        _f(element.standard_atomic_weight),
        _f(element.pauling_electronegativity),
        _f(element.covalent_radius_pm),
        _f(element.vdw_radius_pm),
        float(element.valence_electrons),
        float(element.group),
        float(element.period),
    ]


# ──────────────────────────────────────────────────────────────────────
# ElementTable
# ──────────────────────────────────────────────────────────────────────


class ElementTable:
    """Read-only registry indexed by symbol or atomic number.

    Symbols are ordered by ascending atomic number; this ordering is
    the canonical composition-axis layout. `mass_tensor[i]` corresponds
    to the element at `symbols[i]`.

    `feature_tensor` is indexed by atomic number (row 0 is padding) so
    graph-NN code can do `feature_tensor.index_select(0, Z)` directly
    on a Z-tensor. This is a different indexing scheme from
    `mass_tensor` — intentional; the two have different consumers.
    """

    __slots__ = (
        "_elements",
        "_by_symbol",
        "_by_z",
        "_symbols",
        "_index_by_symbol",
        "_mass_tensor",
        "_feature_tensor",
    )

    def __init__(self, elements: list[Element]):
        elements = sorted(elements, key=lambda e: e.atomic_number)
        self._elements: tuple[Element, ...] = tuple(elements)
        self._by_symbol: dict[str, Element] = {e.symbol: e for e in self._elements}
        self._by_z: dict[int, Element] = {e.atomic_number: e for e in self._elements}
        self._symbols: tuple[str, ...] = tuple(e.symbol for e in self._elements)
        self._index_by_symbol: dict[str, int] = {
            s: i for i, s in enumerate(self._symbols)
        }
        # Mass tensor — composition-axis ordering, float64 for monoisotopic precision.
        self._mass_tensor: torch.Tensor = torch.tensor(
            [e.monoisotopic_mass for e in self._elements], dtype=torch.float64
        )
        # Feature tensor — Z-indexed, float32 (with NaN for missing fields).
        z_max = max(e.atomic_number for e in self._elements)
        feat = torch.full(
            (z_max + 1, len(FEATURE_COLUMNS)), float("nan"), dtype=torch.float32
        )
        for e in self._elements:
            feat[e.atomic_number] = torch.tensor(
                _element_to_feature_row(e), dtype=torch.float32
            )
        self._feature_tensor: torch.Tensor = feat

    # ── lookup ────────────────────────────────────────────────────
    def __getitem__(self, key: str | int) -> Element:
        if isinstance(key, int):
            try:
                return self._by_z[key]
            except KeyError:
                raise KeyError(f"no element with atomic number {key}") from None
        try:
            return self._by_symbol[key]
        except KeyError:
            raise KeyError(f"unknown element symbol: {key!r}") from None

    def __contains__(self, key: object) -> bool:
        if isinstance(key, int):
            return key in self._by_z
        if isinstance(key, str):
            return key in self._by_symbol
        return False

    def __iter__(self) -> Iterator[Element]:
        return iter(self._elements)

    def __len__(self) -> int:
        return len(self._elements)

    # ── canonical ordering ────────────────────────────────────────
    @property
    def symbols(self) -> tuple[str, ...]:
        """Composition-axis ordering — symbols by ascending atomic number."""
        return self._symbols

    def index(self, symbol: str) -> int:
        """Composition-axis position for a symbol. Inverse of `symbols`."""
        try:
            return self._index_by_symbol[symbol]
        except KeyError:
            raise KeyError(f"unknown element symbol: {symbol!r}") from None

    # ── tensor views ──────────────────────────────────────────────
    @property
    def mass_tensor(self) -> torch.Tensor:
        """1-D float64, monoisotopic masses indexed by composition axis."""
        return self._mass_tensor

    @property
    def feature_tensor(self) -> torch.Tensor:
        """(Z_max+1, F) float32, indexed by atomic number; row 0 is padding.

        Column order: see `FEATURE_COLUMNS`. NaN where a field is undefined
        for an element (e.g. noble-gas electronegativity, synthetic-element
        radii). Padding row is all-NaN.
        """
        return self._feature_tensor


# ──────────────────────────────────────────────────────────────────────
# Load elements.json and build the singleton
# ──────────────────────────────────────────────────────────────────────


def _load_elements() -> list[Element]:
    with resources.files("constellation.data").joinpath("elements.json").open("r") as fh:
        doc = json.load(fh)
    out: list[Element] = []
    for rec in doc["elements"]:
        isotopes = tuple(
            Isotope(
                mass_number=i["mass_number"],
                exact_mass=i["exact_mass"],
                abundance=i["abundance"],
            )
            for i in rec["isotopes"]
        )
        out.append(
            Element(
                symbol=rec["symbol"],
                atomic_number=rec["atomic_number"],
                monoisotopic_mass=rec["monoisotopic_mass"],
                standard_atomic_weight=rec["standard_atomic_weight"],
                isotopes=isotopes,
                pauling_electronegativity=rec["pauling_electronegativity"],
                covalent_radius_pm=rec["covalent_radius_pm"],
                vdw_radius_pm=rec["vdw_radius_pm"],
                valence_electrons=rec["valence_electrons"],
                group=rec["group"],
                period=rec["period"],
            )
        )
    return out


ELEMENTS: ElementTable = ElementTable(_load_elements())
ELEMENT_SYMBOLS: tuple[str, ...] = ELEMENTS.symbols

# Legacy MS view alias — CHNOPS-6, the cartographer hot-path tuple.
# Kept for ergonomics, but ELEMENT_SYMBOLS is the canonical ordering.
ELEMENT_TYPES: tuple[str, ...] = ("C", "H", "N", "O", "S", "P")

# Derived element-mass dict views. Pure import-time views over ELEMENTS,
# pinned together by the test suite — no separate maintenance.
MASSES: dict[str, float] = {s: ELEMENTS[s].monoisotopic_mass for s in ELEMENT_SYMBOLS}
WEIGHTS: dict[str, float | None] = {
    s: ELEMENTS[s].standard_atomic_weight for s in ELEMENT_SYMBOLS
}


__all__ = [
    "Isotope",
    "Element",
    "ElementTable",
    "ELEMENTS",
    "ELEMENT_SYMBOLS",
    "ELEMENT_TYPES",
    "MASSES",
    "WEIGHTS",
    "FEATURE_COLUMNS",
    "PROTON_MASS",
    "ELECTRON_MASS",
    "NEUTRON_MASS",
    "ISOTOPE_MASS_DIFF",
    "AVOGADRO",
]
