#!/usr/bin/env bash
# Install BUSCO into Constellation's third_party/ layout.
#
# BUSCO is fundamentally a conda tool: bioconda bundles its 8 external
# aligners (metaeuk / hmmer / prodigal / sepp / bbmap / augustus / blast /
# miniprot), which a bare pip install does NOT provide — so a pip-only
# BUSCO cannot actually run. This installer therefore creates a *dedicated
# conda environment* (a prefix env under third_party/) so BUSCO and its
# aligners are fully isolated from the main `constellation` env. That
# isolation is also why BUSCO is no longer listed in environment.yml: it
# pins numpy<2.4, which would otherwise downgrade the core env's numpy>=2
# (needed by torch 2.5.x + pyarrow>=18).
#
# Layout (matches the thirdparty.registry contract — artifact 'busco'):
#   third_party/busco/<version>/env/         (the conda prefix env)
#   third_party/busco/<version>/busco        (wrapper -> runs busco in env)
#   third_party/busco/current -> <version>/  (symlink)
#
# The 'busco' wrapper invokes `conda run -p <env>` so the env's activate.d
# hooks (e.g. AUGUSTUS_CONFIG_PATH) and bundled aligners resolve at
# runtime — not just PATH. Requires conda or mamba on PATH.
#
# Lineage data: set $BUSCO_DOWNLOADS_PATH (the runner passes it through as
# `--download_path --offline`), or pre-stage with --lineage. Override the
# tool location with $CONSTELLATION_BUSCO_HOME.
#
# Usage:
#   bash scripts/install-busco.sh
#   bash scripts/install-busco.sh --force
#   bash scripts/install-busco.sh --version 6.1.0
#   bash scripts/install-busco.sh --lineage eukaryota_odb12   # pre-stage a dataset
#
# BUSCO is MIT-licensed.
set -euo pipefail

VERSION="6.1.0"
LINEAGE=""
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

force=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --force) force=1; shift ;;
        --version) VERSION="$2"; shift 2 ;;
        --lineage) LINEAGE="$2"; shift 2 ;;
        -h|--help)
            cat <<'USAGE'
install-busco.sh — install BUSCO into a dedicated conda env.

BUSCO needs its 8 bioconda-bundled aligners (metaeuk/hmmer/...) to run, so
this installer creates an isolated conda prefix env rather than a pip venv.
BUSCO is intentionally NOT in environment.yml (it pins numpy<2.4, which
would downgrade the core env). Requires conda or mamba on PATH.

Writes to:
  third_party/busco/<version>/env/         (conda prefix env)
  third_party/busco/<version>/busco        (wrapper)
  third_party/busco/current -> <version>/   (symlink)

Lineage data: set $BUSCO_DOWNLOADS_PATH, or pre-stage with --lineage NAME.
Override the tool path via $CONSTELLATION_BUSCO_HOME.

BUSCO is MIT-licensed.
USAGE
            exit 0
            ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

# BUSCO requires conda/mamba (bioconda bundles its aligners). Prefer mamba
# for faster solves; fall back to conda.
CONDA_BIN="$(command -v mamba || command -v conda || true)"
if [[ -z "${CONDA_BIN}" ]]; then
    echo "error: neither mamba nor conda is on PATH" >&2
    echo "  BUSCO + its aligners are only distributed via bioconda; install a" >&2
    echo "  conda/mamba (e.g. miniforge) first, then re-run this script." >&2
    exit 1
fi

TARGET_DIR="${REPO_ROOT}/third_party/busco/${VERSION}"
ENV_PREFIX="${TARGET_DIR}/env"
CURRENT_LINK="${REPO_ROOT}/third_party/busco/current"
ENTRY="${TARGET_DIR}/busco"

if [[ -e "${ENTRY}" && ${force} -eq 0 ]]; then
    echo "busco ${VERSION} already installed at ${ENTRY}"
else
    rm -rf "${TARGET_DIR}"
    mkdir -p "${TARGET_DIR}"
    echo "creating dedicated conda env for BUSCO ${VERSION} (this can take a few minutes)..."
    # conda-forge before bioconda + strict priority — same rationale as
    # environment.yml's channel order. The env carries its own numpy<2.4,
    # isolated from the core constellation env.
    "${CONDA_BIN}" create -y --strict-channel-priority -p "${ENV_PREFIX}" \
        -c conda-forge -c bioconda "busco=${VERSION}"

    if [[ ! -x "${ENV_PREFIX}/bin/busco" ]]; then
        echo "error: busco not found in the conda env after install (${ENV_PREFIX}/bin/busco)" >&2
        exit 1
    fi

    # Emit a wrapper so the registry artifact 'busco' runs the tool inside
    # its env. `conda run` sources the env's activate.d hooks (e.g.
    # AUGUSTUS_CONFIG_PATH) and puts the bundled aligners on PATH. If this
    # conda lacks --no-capture-output (very old, or micromamba), fall back
    # to a PATH-export wrapper (covers the default metaeuk mode; skips
    # activate.d hooks). Absolute paths are baked in so the `current`
    # symlink swap stays transparent.
    if "${CONDA_BIN}" run --help 2>/dev/null | grep -q -- '--no-capture-output'; then
        cat > "${ENTRY}" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install-busco.sh — runs BUSCO inside its
# dedicated conda env (bundled aligners + activate.d hooks resolve).
exec "${CONDA_BIN}" run --no-capture-output -p "${ENV_PREFIX}" busco "\$@"
EOF
    else
        cat > "${ENTRY}" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install-busco.sh — PATH-export fallback
# (this conda lacks 'conda run --no-capture-output').
export PATH="${ENV_PREFIX}/bin:\$PATH"
exec "${ENV_PREFIX}/bin/busco" "\$@"
EOF
    fi
    chmod +x "${ENTRY}"
fi

tmp_link="${CURRENT_LINK}.tmp.$$"
ln -sfn "${VERSION}" "${tmp_link}"
mv -Tf "${tmp_link}" "${CURRENT_LINK}"

if [[ -n "${LINEAGE}" ]]; then
    dl="${BUSCO_DOWNLOADS_PATH:-${HOME}/.constellation/busco_downloads}"
    echo "pre-staging lineage ${LINEAGE} into ${dl}..."
    "${ENTRY}" --download_path "${dl}" --download "${LINEAGE}" || \
        echo "warning: lineage download failed; fetch manually with \`busco --download ${LINEAGE}\`" >&2
fi

echo "installed: ${ENTRY}"
echo "current:   ${CURRENT_LINK} -> ${VERSION}/"
echo
echo "run \`constellation doctor\` to confirm registry discovery."
