#!/usr/bin/env bash
# Install Ragout into Constellation's third_party/ layout.
#
# Ragout (Reference-Assisted Genome Ordering UTility — multi-reference,
# rearrangement-aware chromosome scaffolding) is distributed on bioconda,
# where it pins **Python 3.8** and bundles Sibelia (its default synteny
# backend). Because of the Python pin it CANNOT live in the main
# `constellation` env (Python 3.12), so this installer creates a dedicated
# conda prefix env. (HAL alignments from Progressive Cactus are an optional
# synteny backend for large genomes — install scripts/install-progressive-
# cactus.sh separately if you need it; not required here.)
#
# Layout (matches the thirdparty.registry contract — artifact 'ragout'):
#   third_party/ragout/<version>/env/         (the conda prefix env)
#   third_party/ragout/<version>/ragout       (wrapper -> runs ragout in env)
#   third_party/ragout/current -> <version>/  (symlink)
#
# Requires conda or mamba on PATH. Override the tool location with
# $CONSTELLATION_RAGOUT_HOME.
#
# Usage:
#   bash scripts/install-ragout.sh
#   bash scripts/install-ragout.sh --force
#   bash scripts/install-ragout.sh --version 2.3
#
# Ragout is BSD-3-Clause-licensed.
set -euo pipefail

VERSION="2.3"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

force=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --force) force=1; shift ;;
        --version) VERSION="$2"; shift 2 ;;
        -h|--help)
            cat <<'USAGE'
install-ragout.sh — install Ragout into a dedicated conda env.

Ragout pins Python 3.8 on bioconda, so it gets its own isolated conda
prefix env rather than sharing the constellation 3.12 env. Sibelia (its
default synteny backend) is bundled by the conda package. Requires conda
or mamba on PATH.

Writes to:
  third_party/ragout/<version>/env/         (conda prefix env)
  third_party/ragout/<version>/ragout       (wrapper)
  third_party/ragout/current -> <version>/   (symlink)

Override the tool path via $CONSTELLATION_RAGOUT_HOME.

Ragout is BSD-3-Clause-licensed.
USAGE
            exit 0
            ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

CONDA_BIN="$(command -v mamba || command -v conda || true)"
if [[ -z "${CONDA_BIN}" ]]; then
    echo "error: neither mamba nor conda is on PATH" >&2
    echo "  Ragout (and its bundled Sibelia) are distributed via bioconda;" >&2
    echo "  install a conda/mamba (e.g. miniforge) first, then re-run." >&2
    exit 1
fi

TARGET_DIR="${REPO_ROOT}/third_party/ragout/${VERSION}"
ENV_PREFIX="${TARGET_DIR}/env"
CURRENT_LINK="${REPO_ROOT}/third_party/ragout/current"
ENTRY="${TARGET_DIR}/ragout"

if [[ -e "${ENTRY}" && ${force} -eq 0 ]]; then
    echo "ragout ${VERSION} already installed at ${ENTRY}"
else
    rm -rf "${TARGET_DIR}"
    mkdir -p "${TARGET_DIR}"
    echo "creating dedicated conda env for Ragout ${VERSION} (this can take a few minutes)..."
    # conda-forge before bioconda + strict priority — matches environment.yml.
    # The env carries its own Python 3.8, isolated from the core env.
    "${CONDA_BIN}" create -y --strict-channel-priority -p "${ENV_PREFIX}" \
        -c conda-forge -c bioconda "ragout=${VERSION}"

    if [[ ! -x "${ENV_PREFIX}/bin/ragout" ]]; then
        echo "error: ragout not found in the conda env after install (${ENV_PREFIX}/bin/ragout)" >&2
        exit 1
    fi

    # Wrapper so the registry artifact 'ragout' runs the tool inside its
    # env (so the bundled Sibelia and the env's Python 3.8 resolve). Prefer
    # `conda run`; fall back to a PATH-export wrapper on very old conda /
    # micromamba. Absolute paths baked in (the `current` symlink stays
    # transparent).
    if "${CONDA_BIN}" run --help 2>/dev/null | grep -q -- '--no-capture-output'; then
        cat > "${ENTRY}" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install-ragout.sh — runs Ragout inside its
# dedicated conda env (bundled Sibelia + Python 3.8 resolve).
exec "${CONDA_BIN}" run --no-capture-output -p "${ENV_PREFIX}" ragout "\$@"
EOF
    else
        cat > "${ENTRY}" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install-ragout.sh — PATH-export fallback
# (this conda lacks 'conda run --no-capture-output').
export PATH="${ENV_PREFIX}/bin:\$PATH"
exec "${ENV_PREFIX}/bin/ragout" "\$@"
EOF
    fi
    chmod +x "${ENTRY}"
fi

tmp_link="${CURRENT_LINK}.tmp.$$"
ln -sfn "${VERSION}" "${tmp_link}"
mv -Tf "${tmp_link}" "${CURRENT_LINK}"

echo "installed: ${ENTRY}"
echo "current:   ${CURRENT_LINK} -> ${VERSION}/"
echo
echo "run \`constellation doctor\` to confirm registry discovery."
